### ISSUE TITLE
The align-top has wrong syntax

### ISSUE THREAD

**Issue by vbaimas** [markgreenall/StringBean#19]
The align-top has wrong syntax :
 From :  `.align-top { verical-align:top; } `
 To : `align-top {vertical-align:top;}`

**Comment by markgreenall** [comment]
Hi vbaimas,

Thank you for finding that issue.  I have fixed it in the branch "v2.2", and have merged that into Master.

All the best,
Mark

**Comment by vbaimas** [comment]
Hello @markgreenall ,
There is no reason to thank me.. My pleasure! 
All the best too,
Vasilis
